[package]
name = "crypto-formalization"
version = "0.16.18"
lean_version = "leanprover-community/lean:3.49.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "46ae64dc15f6dc8eda1654dd8e7faa3b21bb6cbe"}
