[package]
name = "lean-crypto-formalization"
version = "0.16.18"
lean_version = "leanprover-community/lean:3.50.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "1e3201306d4d9eb1fd54c60d7c4510ad5126f6f9"}
