
on:
  push:

jobs:
  # Cancels previous runs of jobs in this file
  cancel:
    if: github.repository == 'leanprover-community/mathlib'
    name: 'Cancel Previous Runs (CI)'
    runs-on: ubuntu-latest
    # timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

  update_lean_xyz_branch_and_build:
    runs-on: ubuntu-latest
    name: Update lean-x.y.z branch and build project
    steps:

    - name: checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: update branch
      if: github.ref == 'refs/heads/master'
      uses: leanprover-contrib/update-versions-action@master

    - name: build project
      uses: leanprover-contrib/lean-build-action@master

  style_lint:
    name: Lint style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: lint
        run: |
          ./scripts/lint-style.sh

  lint:
    name: Lint mathlib
    runs-on: ubuntu-latest

    steps:
      - name: clean build directory
        if: ${{ 1 }}
        run: rm -rf ./* ./.??*

      - name: retrieve build
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.build.outputs.artifact_name }}

      - name: untar build
        run: tar -xf workspace.tar

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: lint
        run: |
          ./scripts/mk_all.sh
          lean --run scripts/lint_mathlib.lean --github
          rm src/all.lean
      
      - name: clean up working directory and elan
        if: always() && ${{ 1 }}
        run: rm -rf * $HOME/.elan